POST http://localhost:3000/api/patients
Content-Type: application/json

{
  "name": "Alex Man",
  "ssn": "135-45-6789",
  "dateOfBirth": "1980-01-01",
  "gender": "female",
  "occupation": "Fireman"
}
